name = "HelpPlots"
uuid = "5880b2e8-ad0a-48c9-bacd-30dc9c1357e0"
authors = ["Min-Gu Yoo <mgyoo86@gmail.com> and contributors"]
version = "1.0.0"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
HelpPlotsExt = "Plots"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
